sources:
  - name: UserAPI
    handler:
      openapi:
        baseUrl: http://localhost:3001/
        source: http://localhost:3001/api-docs.json
        operationHeaders:
          Authorization: "{context.headers.authorization}"
  - name: ArticleAPI
    handler:
      openapi:
        baseUrl: http://localhost:3002/
        source: http://localhost:3002/api-docs.json
        operationHeaders:
          Authorization: "{context.headers.authorization}"

  