sources:
  - name: UserAPI
    handler:
      openapi:
        baseUrl: "${USER_API_HOST}"
        source: "${USER_API_HOST}/api-docs.json"
        operationHeaders:
          Authorization: "{context.headers.authorization}"
  - name: ArticleAPI
    handler:
      openapi:
        baseUrl: "${ARTICLE_API_HOST}"
        source: "${ARTICLE_API_HOST}/api-docs.json"
        operationHeaders:
          Authorization: "{context.headers.authorization}"

  